[package]
name = "bitcoin"
version = "1.1.0"
authors = ["Interlay <contact@interlay.io>"]
edition = "2018"

[features]
default = []
regtest-mine-on-tx = []
regtest-manual-mining = []
cli = ["clap"]
uses-bitcoind = []

[dependencies]
thiserror = "1.0"
bitcoincore-rpc = { git = "https://github.com/rust-bitcoin/rust-bitcoincore-rpc", rev = "d9a1dd014f8eff8b00618457bb6b845c8b932bb7" }
hex = "0.4.2"
async-trait = "0.1.40"
tokio = { version = "1.0", features = ["full"] }
backoff = { version = "0.3.0", features = ["tokio"] }
clap = { version = "3.1", features = ["derive", "std", "env"], optional = true }
num = "0.2"
num-traits = "0.2"
num-derive = "0.3"
futures = "0.3.5"
serde_json = "1.0.71"
log = "0.4.0"
hyper = "0.10"
esplora-btc-api = "1.0.3"
reqwest = "0.11.11"

# Substrate dependencies
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }

[dev-dependencies]
mockall = "0.8.1"
regex = "1.4.3"
rand = { version = "0.7" }
